spring:
  application:
    name: organization
  data:
    mongodb:
      uri: mongodb://localhost/mydb
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

server:
  port:  8082    