apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.105
    path: "/mnt/sharedfolder/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.105
    path: "/mnt/sharedfolder/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.105
    path: "/mnt/sharedfolder/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.105
    path: "/mnt/sharedfolder/pv3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.105
    path: "/mnt/sharedfolder/pv4"
